### ISSUE TITLE
After isLoading false inside data and views will not appear

### ISSUE THREAD

**Issue by akiladevinda** [alexZajac/react-native-skeleton-content-nonexpo#12]
I have set SkeltonContent for loading my data from the back end. Once the loading finishes redux returns false and SkeltonConeten disappear and my view is not render

Code : 

```
<SkeletonContent
            isLoading={this.props.fetchRequest}
            containerStyle={{flex: 1, width: 300, flexDirection: 'row'}}
            animationDirection="horizontalLeft"
            layout={[
              // long line
              {width: 220, height: 200, marginBottom: 6},
              // short line
              {width: 180, height: 180, marginBottom: 6},
            ]}>
            <FlatList
              horizontal
              style={styles.list}
              data={this.props.fetchData}
              showsHorizontalScrollIndicator={false}
              keyExtractor={item => {
                return item.id;
              }}
              ItemSeparatorComponent={() => {
                return <View style={{marginLeft: 10}} />;
              }}
              renderItem={({item}) => {
                const dateISO = item.createdAt;
                const date = dateISO.split('T');

                return (
                  <TouchableOpacity
                    style={styles.projectCardContainer}
                    onPress={() => this.navigationClickListner(item)}>
                    <View style={styles.buttonViewConatiner}>
                      <Image
                        source={Images.HOME_PROJ_ICON}
                        style={styles.buttonImage}
                      />
                      <Text style={styles.buttonTextRight}>{item.name}</Text>
                      <Text style={styles.buttonTextRightDate}>{date[0]}</Text>
                    </View>
                  </TouchableOpacity>
                );
              }}
            />
          </SkeletonContent>
```

**Comment by alexZajac** [comment]
Hey @akiladevinda. Can you provide a working snack or environment for me to test the behavior? Please refer to the issue templates, thanks!

**Comment by alexZajac** [comment]
With the new release I don't think that this behavior is coming from the internal logic, closing it for now.

**Comment by komalharmale** [comment]
> With the new release I don't think that this behavior is coming from the internal logic, closing it for now.

i am also facing this same issue flatlist not showing inside <SkeletonContent>

**Comment by komalharmale** [comment]
> I have set SkeltonContent for loading my data from the back end. Once the loading finishes redux returns false and SkeltonConeten disappear and my view is not render
> 
> Code :
> 
> ```
> <SkeletonContent
>             isLoading={this.props.fetchRequest}
>             containerStyle={{flex: 1, width: 300, flexDirection: 'row'}}
>             animationDirection="horizontalLeft"
>             layout={[
>               // long line
>               {width: 220, height: 200, marginBottom: 6},
>               // short line
>               {width: 180, height: 180, marginBottom: 6},
>             ]}>
>             <FlatList
>               horizontal
>               style={styles.list}
>               data={this.props.fetchData}
>               showsHorizontalScrollIndicator={false}
>               keyExtractor={item => {
>                 return item.id;
>               }}
>               ItemSeparatorComponent={() => {
>                 return <View style={{marginLeft: 10}} />;
>               }}
>               renderItem={({item}) => {
>                 const dateISO = item.createdAt;
>                 const date = dateISO.split('T');
> 
>                 return (
>                   <TouchableOpacity
>                     style={styles.projectCardContainer}
>                     onPress={() => this.navigationClickListner(item)}>
>                     <View style={styles.buttonViewConatiner}>
>                       <Image
>                         source={Images.HOME_PROJ_ICON}
>                         style={styles.buttonImage}
>                       />
>                       <Text style={styles.buttonTextRight}>{item.name}</Text>
>                       <Text style={styles.buttonTextRightDate}>{date[0]}</Text>
>                     </View>
>                   </TouchableOpacity>
>                 );
>               }}
>             />
>           </SkeletonContent>
> ```

hi did you find any solution on this?
