### ISSUE TITLE
Reanimated v2 error

### ISSUE THREAD

**Issue by dinhmai74** [alexZajac/react-native-skeleton-content-nonexpo#17]
**Describe the bug**
Not working with reanimated v2
Got error interpolate is not a function
**To Reproduce**
Reanimated v2 rename interpolate to interpolateNode
https://docs.swmansion.com/react-native-reanimated/docs/migration
**Screenshots**
![image](https://user-images.githubusercontent.com/40544043/84635764-dd4dd780-af1d-11ea-863c-9340383f83c0.png)

**Comment by alexZajac** [comment]
Hey @dinhmai74!
Yes, it's an issue, but I chose not to upgrade on `reanimated-v2` since it's still in alpha release and there is not a stable one. If they get a stable release or if it blocks too many builds, I will update it.

**Comment by Harkindey** [comment]
@alexZajac can you make a version that works with reanimated-v2 and also make it alpha or a test version,  reanimated@v2.0.0-alpha8 seems stable to me 🥺.

**Comment by yzlin** [comment]
@alexZajac reanimated@v2.0.0 has been released. please help to update.
