### ISSUE TITLE
Excessive number of pending callbacks

### ISSUE THREAD

**Issue by mernxl** [alexZajac/react-native-skeleton-content-nonexpo#18]
**Describe the bug**
Hello, i am getting some warnings **sometimes** when using the latest version (1.0.9) implemented using hooks. There are ScreenShots below which indicating the warnings i get. 

I am suggesting this is as a result of the change from a normal class component to a functional component. 
Also, i think the class component would be a better approach as we don't need to create all those functions before we render.

- Also, i strongly think the code needs optimising, examples Animated Values are created on each render, functions are not reused, they are recreated on each render. 
The functions below are called on every render even if we are not using shiver animation type (created constants are only used when create shiver bones).
```ts
...
const gradientStart = getGradientStartDirection();
const gradientEnd = getGradientEndDirection();
...
```

**To Reproduce**
1. Create Many components with SkeletonContent
2. Run application with remote debugging

**Expected behavior**

**Screenshots**
1. This warning only appear in the browser console when doing remote debugging.
![image](https://user-images.githubusercontent.com/16241595/85756831-100a8380-b707-11ea-9825-32813508ba03.png)

1. I get this other warning in a Flatlist component with as little as 10 renderItems. Each item is a static component wrapped with the SkeletonContent HOC. It should be noted that i did not get this when using previous versions of the package.
![image](https://user-images.githubusercontent.com/16241595/85819522-d3bd3e80-b76b-11ea-8be4-40068dfeda8f.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3 - Emulated
 - OS: Android 9
 - Package version: 1.0.9

**Additional context**

**Comment by hannojg** [comment]
Huh, ran into the same issue with the latest version `1.0.11`

```
Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"2662":{},"15933":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"16204":
{"module":"ReanimatedModule","method":"getValue"},"16212":{"module":"ReanimatedModule","method":"getValue"},"16237":
{"module":"ReanimatedModule","method":"getValue"},"16257":{"module":"ReanimatedModule","method":"getValue"},"16264":
{"module":"ReanimatedModule","method":"getValue"},"16274":{"module":"ReanimatedModule","method":"getValue"},"16292":
{"module":"ReanimatedModule","method":"getValue"},"16336":{},"16343":
{"module":"ReanimatedModule","method":"getValue"},"16353":{"module":"ReanimatedModule","method":"getValue"},"16368":
{"module":"ReanimatedModule","method":"getValue"},"16377":{"module":"ReanimatedModule","method":"getValue"},"16389":
{"module":"ReanimatedModule","method":"getValue"},"16397":{"module":"ReanimatedModule","method":"getValue"},"16422":
{"module":"ReanimatedModule","method":"getValue"},"16442":{"module":"ReanimatedModule","method":"getValue"},"16449":
{"module":"ReanimatedModule","method":"getValue"},"16459":{"module":"ReanimatedModule","method":"getValue"},"16477":
{"module":"ReanimatedModule","method":"getValue"},"16521":{},"16528":
{"module":"ReanimatedModule","method":"getValue"},"16538":{"module":"ReanimatedModule","method":"getValue"},"16553":
{"module":"ReanimatedModule","method":"getValue"},"16562":{"module":"ReanimatedModule","method":"getValue"},"16574":
{"module":"ReanimatedModule","method":"getValue"},"16582":{"module":"ReanimatedModule","method":"getValue"},"16607":
{"module":"ReanimatedModule","method":"getValue"},"16627":{"module":"ReanimatedModule","method":"getValue"},"16634":
{"module":"ReanimatedModule","method":"getValue"},"16644":{"module":"ReanimatedModule","method":"getValue"},"16662":
{"module":"ReanimatedModule","method":"getValue"},"16706":{},"16713":
{"module":"ReanimatedModule","method":"getValue"},"16723":{"module":"ReanimatedModule","method":"getValue"},"16738":
{"module":"ReanimatedModule","method":"getValue"},"16747":{"module":"ReanimatedModule","method":"getValue"},"16759":
{"module":"ReanimatedModule","method":"getValue"},"16767":{"module":"ReanimatedModule","method":"getValue"},"16792":
{"module":"ReanimatedModule","method":"getValue"},"16812":{"module":"ReanimatedModule","method":"getValue"},"16819":
{"module":"ReanimatedModule","method":"getValue"},"16829":{"module":"ReanimatedModule","method":"getValue"},"16847":
{"module":"ReanimatedModule","method":"getValue"},"16891":{},"16898":
{"module":"ReanimatedModule","method":"getValue"},"16908":{"module":"ReanimatedModule","method":"getValue"},"16923":
{"module":"ReanimatedModule","method":"getValue"},"16932":{"module":"ReanimatedModule","method":"getValue"},"...
(truncated keys)...":451}

**Comment by greifmatthias** [comment]
Same, any update on this?

**Comment by mernxl** [comment]
Hi, that issue is caused by `react native reanimation` lib. Locally I have reverted to using methods and Components on the `react-native`  package itself.

I don't seem to have this issue anymore. I can't really create a merge request for that given its a big breaking change.

What I will do is I will create a branch and upload the code on my fork. I will comment here when I push the changes.

**Comment by mernxl** [comment]
Hello @hannojg i finally pushed the my version of this library, check [the commit](https://github.com/mernxl/react-native-skeleton-content-nonexpo/commit/364518efeb456b84f7782a29028f28a8e79ae90b) on [my fork](https://github.com/mernxl/react-native-skeleton-content-nonexpo).

I really believe there some performance boost after all the changes, I would love reviews and feedback. Thanks
