### ISSUE TITLE
animate can not run when remote debugging in hermes engine

### ISSUE THREAD

**Issue by lukmanhidayah** [alexZajac/react-native-skeleton-content-nonexpo#2]

**Comment by alexZajac** [comment]
Hello @lukmanhidayah !
Can you provide me more elements and context about your issue so that I can take care of it?

**Comment by hoanglam10499** [comment]
same

**Comment by alexZajac** [comment]
Hey @hoanglam10499 @lukmanhidayah . Can you guys give more context on that? Please refer to the issue guidelines, thanks!

**Comment by alexZajac** [comment]
Hello guys, 

I have successfully enabled `Hermes Engine` in a react native app not managed by expo, and I wasn't able to reproduce the issue, I will close it for now.

If you have a small demo or project with which it still doesn't work, please reopen and provide a testable envrionment.
