### ISSUE TITLE
diagonal animation is not working

### ISSUE THREAD

**Issue by lore93** [alexZajac/react-native-skeleton-content-nonexpo#20]
**Describe the bug**
After creating the component I set the animationDirection to "diagonalDownRight" (the problem arise also with "diagonalTopRight","diagonalDownLeft" and "diagonalTopLeft") . The behavior of the animation is not what I expected. Look the gif:
![skeleton](https://user-images.githubusercontent.com/15127763/86118620-5c700d80-bad1-11ea-9cb9-34178af4c54c.gif)

**To Reproduce**

import SkeletonContent from "react-native-skeleton-content-nonexpo";

<SkeletonContent
        boneColor={"#f1f1f1"}
        highlightColor={"#fafafa"}
        isLoading={true}
        duration={1000}
        animationDirection={"diagonalDownRight"}
        layout={[
          {
            width: 100,
            height:100,
            marginBottom: 32,
            marginTop: 32,
          }
       ]}
/>

**Expected behavior**
I would expect to see the animation starting from the top left corner and ending to the bottom right:
![image](https://user-images.githubusercontent.com/15127763/86117627-aa841180-bacf-11ea-8f43-5769b61b8e9a.png)

**Additional context**
I'm running React native v0.61.5 and react-native-skeleton-content-nonexpo v1.0.9

**Comment by alexZajac** [comment]
Hey guys, just to let you know about my progress, I am making a change in order for the diagonal gradients to display properly, expect to see the change deployed in the next few days! 😉
