### ISSUE TITLE
Animated components taking forever to mount & initially render

### ISSUE THREAD

**Issue by henryjeff** [alexZajac/react-native-skeleton-content-nonexpo#21]
**Describe the bug**
We recently started using this skeleton content package but it seems to be taking forever for the actual animated components to mount and render. This [screenshot](https://cdn.discordapp.com/attachments/517087158696280067/730609336589615155/836d04fba2be3a54bda65ddfb0df5ba3-png.png) shows rendering 10 of our UserItems which are all in their skeletal state, and you can see rendering all 10 takes upwards of 500ms!

**To Reproduce**
- Just using the package

**Expected behavior**
- Is this the expected behavior? 

**Smartphone (please complete the following information):**
 - Device: IPhone Simulator
 - OS: iOS 13.4
 - Package version: 1.0.10

**Additional context**
I guess I'm just wondering if this is normal or if we are using this package wrong. Is rendering this many instances of skeletal components not ideal? We are just confused as to what to even do at this point.

**Comment by xwg2015** [comment]
the same problem

**Comment by alexZajac** [comment]
As there weren't any follow-ups here, closing the ticket for now until we have more data points on bug reproducibility and ways to solve it.
