### ISSUE TITLE
operator 'abs' not found

### ISSUE THREAD

**Issue by lyseiha** [alexZajac/react-native-skeleton-content-nonexpo#25]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-14 at 13 56 16](https://user-images.githubusercontent.com/26889046/90222261-ee3f9a00-de35-11ea-988e-e1a6c808727a.png)

**Comment by Dimasprog** [comment]
@lyseiha, the same for me. Did you find some solutions?

**Comment by leena-sharma** [comment]
@Dimasprog @lyseiha  facing same issue. Did anyone find solution?

**Comment by Dimasprog** [comment]
> @Dimasprog @lyseiha facing same issue. Did anyone find solution?

No, i didn't. I used react-native-skeleton-content

**Comment by kucharzgotuje** [comment]
+1

**Comment by Dimasprog** [comment]
> +1

@kucharzgotuje Hey, try to use react-native-skeleton-content

**Comment by kucharzgotuje** [comment]
> @kucharzgotuje Hey, try to use react-native-skeleton-content

Tried :/
I had other issues. I don't have expo in my project so this would be best solution for me. Nevermind, in worst case scenario I will replace it with some spinner or something :P

**Comment by jamesjara** [comment]
it's currently using an older version of react-native reanimated, use the resolution to use 1.9.0
```
  "resolutions": {
    "react-native-skeleton-content-nonexpo/react-native-reanimated": "~1.9.0"
  },
```

**Comment by alexZajac** [comment]
It seems like the root cause of the issue was using the nonexpo version of the package whereas the expo version was supposed to be used. Ressolving
