### ISSUE TITLE
Android App is crashing

### ISSUE THREAD

**Issue by ariangel** [alexZajac/react-native-skeleton-content-nonexpo#27]
**Describe the bug**
After downloading package and cleaning cache, I reinstalled my app and when I open it, it crashes without message error.

**Smartphone**
 - Device: Xiaomi MI A2 Lite
 - OS: Android 9
 - Package version 1.0.11

**Comment by kperreau** [comment]
Same for me.

Samsung S8, react-native: 0.64.0

**Comment by alexZajac** [comment]
Without an error message and stack trace, this is difficult to debug. Updating to the latest version and cleaning previous version should fix it. Resolving due to the timelines of the issue (probably not happening anymore)
