### ISSUE TITLE
any plans for updating the package to use the latest react-native-reanimated

### ISSUE THREAD

**Issue by mouessam** [alexZajac/react-native-skeleton-content-nonexpo#32]
i was just wondering if there is any plans to update the package to use the latest version of react-native-reanimated, because am trying to update my project dep, and I am facing some dep conflict with the versioning issue

**Comment by Razbotics** [comment]
Yes this package doesnt works with reanimated 2

**Comment by alexZajac** [comment]
Hey all! Resolved as of merging [this PR](https://github.com/alexZajac/react-native-skeleton-content-nonexpo/pull/33)
