### ISSUE TITLE
flatlist data not showing inside <SkeletonContent>

### ISSUE THREAD

**Issue by komalharmale** [alexZajac/react-native-skeleton-content-nonexpo#40]
**Describe the bug**
i am fetching some data from api and showing inside the flatlist ...i have use <SkeletonContent to show loding indicator until we dident get api responce..but after getting the api responce i am setting isloding value as false.but flatlist not rendering inside <SkeletonContent /> its showing nothing on screen

**To Reproduce**
1. take  one <SkeletonContent/>
2.inside that add flatlist to show some data
3. check result

**Expected behavior**
expecting flatlist that showing api data after setting isloding value as false

**Smartphone (please complete the following information):**
 - Device:]android/ios any 
 - OS: any
 - PAckage version:1.0.13

**Additional context**
 <SkeletonContent
                containerStyle={{flex: 1, width: '100%'}}
                isLoading={spinner}
                layout={[
                  {key: 'someId', width: 320, height: 20, marginBottom: 6},
                  {key: 'someOther', width: 380, height: 20, marginBottom: 6},
                  {key: 'someOtherId', width: 380, height: 30, marginBottom: 6},
                ]}>
                  <View style={styles.commonmargin}>
                    <View><Text>{spinner}</Text></View>
                <ShowResidentalProject data={residentalProject} />
                </View>
              </SkeletonContent>

**Comment by alexZajac** [comment]
Can we get more context on the bug here? A stack trace of the console on the blank page for example?

**Comment by alexZajac** [comment]
Closing as no update from requester, feel free to re-open if needed!
