### ISSUE TITLE
Animation is not working

### ISSUE THREAD

**Issue by youngseo-im** [alexZajac/react-native-skeleton-content-nonexpo#42]
**Describe the bug**

**Expected behavior**
The current loading is true and the animation is not working.

**Screenshots**

https://user-images.githubusercontent.com/75972718/147809653-939ca8a1-7842-497d-858b-c9eb79abae9e.mov

**Smartphone (please complete the following information):**
 - Device: iPhone11 simulator
 - OS: [e.g. iOS15]
 -  "react-native-skeleton-content-nonexpo": "^1.0.13",
 -     "react-native-reanimated": "^2.2.3",
 -     "react-native-linear-gradient": "^2.5.6",

**Comment by youngseo-im** [comment]
<img width="335" alt="스크린샷 2022-01-01 오후 11 16 49" src="https://user-images.githubusercontent.com/75972718/147852594-48248d8e-ffa5-4f72-9d32-45de8d4e9419.png">

**Comment by droplessjake** [comment]
Bump, I'm using react-native-reanimated 2.2.3 and not seeing any animation.

**Comment by onebigdoor** [comment]
i did not see animation until setting all three `animationType` `boneColor` and `highlightColor` which i had assumed would have had defaults, but i guess not.

**Comment by alexZajac** [comment]
Hi! They are default for these 3: https://github.com/alexZajac/react-native-skeleton-content-nonexpo/blob/master/src/SkeletonContent.tsx#L59-L63

On the issue, it might be that the highlight and bone color are too close to each other to see the pulse difference. If not, I would advise to check the other props and examples.

Closing for now as there was no updates for several months, feel free to reopen if needed.
