### ISSUE TITLE
Not working with react-native-reanimated @ 2.3.0

### ISSUE THREAD

**Issue by karanmartian** [alexZajac/react-native-skeleton-content-nonexpo#43]
Hi,

Could you please help? This is only working with react-native-reanimated @ 2.2.4. From version 2.3.0 onwards of  react-native-reanimated this is crashing the app on launch. Any ideas?

**Comment by alifarooq96** [comment]
@karanmartian I am running into the same issue, were you able to resolve this?

**Comment by karanmartian** [comment]
@alifarooq96 I was able to use v2.3.1 with Expo SDK 44 and the Expo Dev client, it runs well. Dont remember my previous setup now but I was on SDK 43 back then.

**Comment by alexZajac** [comment]
Is this issue still happening?

**Comment by alexZajac** [comment]
Closing as no update from requester, feel free to re-open!
