### ISSUE TITLE
How To Use Childern Layout

### ISSUE THREAD

**Issue by muhammadashariabdillah24** [alexZajac/react-native-skeleton-content-nonexpo#46]
how to use child layout, because I don't use custom layout

Give an example please

**Comment by alexZajac** [comment]
Hey! As this is difficult to give a general example, I preferred to not include any to not bias the implementation in the `README.md`. If you use the children layout, any sized container below the `SkeletonContent` would be translated to a bone loading when `isLoading` is `true`!
