### ISSUE TITLE
Image on SkeletonContent children not loaded

### ISSUE THREAD

**Issue by rhymelody** [alexZajac/react-native-skeleton-content-nonexpo#48]
**Describe the bug**
Image on SkeletonContent children not loaded, when i check avatarLoaded value it's only says false when Image put on SkeletonContent like this, like SkeletonContent not render Image.

<SkeletonContent isLoading={!avatarLoaded}>
  <Image style={styles.avatar} resizeMode="cover" source={avatarImage} onLoad={()=> setAvatarLoaded(true)} />
</SkeletonContent>

when I use Image outside SkeletonContent, image can be loaded, and avatarLoaded value not always false, avatarLoaded value says it's true when fully loaded.

**Expected behavior**
I think all SkeletonContent children should be hidden, but still rendered in React Native. so image can be loaded and set loaded value to SkeletonContent isLoading.

**Comment by alexZajac** [comment]
You could prefetch the image URL and only after set the `isLoading` to `false` since you know that the image is available. I would recommend an effect/high order function to wrap all the events needed for the Skeleton to stop being in loading state before showing content!
