### ISSUE TITLE
App freezing when turning on debug with chrome

### ISSUE THREAD

**Issue by Iamivan1996** [alexZajac/react-native-skeleton-content-nonexpo#53]
**Describe the bug**
Just turning on debug with chrome, then the app is freezing for both Platform OS without any error, all the buttons are not working and also can not scroll down the page until set the props "isLoading" to false.

**To Reproduce**
1. Turning on debug with chrome

**Expected behavior**
Expect in debug and release mode, the animation will works fine and will not effect the app stability 

**Screenshots**
https://user-images.githubusercontent.com/30230906/180197942-a7bdc961-2585-460e-ac81-c8b182048253.mov
![image](https://user-images.githubusercontent.com/30230906/180198100-315d82b0-4a99-49cf-9f4e-b0aebf41a7e1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Simulator , Samsung S22 Ultra
 - OS:  IOS15.5, Android 12
 - Package version:   "react-native-reanimated": "^2.4.1",  "react-native-skeleton-content-nonexpo": "^1.0.13",
 - React Native Version : 0.67.3

**Comment by Cantinaband** [comment]
I'm having the same issue. Any help here?

**Comment by Cantinaband** [comment]
@alexZajac any idea why this happens? It's really a bummer not to use the chrome debugger anymore...

**Comment by fullstack17** [comment]
Is there any updates? I'm still experiencing this issue.

**Comment by ipmcc** [comment]
I have this issue even WITH expo. I've tried Chrome, the WebStorm debugger (which is pretty much just Chrome-by-remote, so not surprising that this doesn't work), and even VSCode, which implements its own debugger, and they all hang. It's not clear whether it's the fault of reanimated or skeleton-content, but both are well-represented in the stack traces I see.

**Comment by The-CodeNinja** [comment]
+1  
Device: Android Emulator, Android 12.0 (S) API-31
react-native-skeleton-content-nonexpo: 1.0.13
react-native-reanimated: 2.10.0
react-native: 0.67.4

**Comment by kiratot** [comment]
Since the library is using react-native-reanimated, the chrome debugger/react native debugger won't work, unfortunately. You need to use Flipper for debugging.

**Comment by ipmcc** [comment]
...which is a _really good_ argument for NOT using reanimated v2. But I digress...

**Comment by alexZajac** [comment]
Hi! We cannot get out of `reanimated-v2`, at least in the current state of the project. 
Closing this one as long as there is no viable option to replace `reanimated-v2`.

**Comment by ipmcc** [comment]
I take issue with the use of the word "cannot" here, as well as the idea that there are no viable alternatives to Reanimated v2 -- RN had animation before Reanimated v2 came along; it's _hardly_ the only option (React.Animated and Reanimated v1 are obvious alternatives) -- but as they say: 'not my circus, not my monkeys.' That aside, it looks like the Reanimated folks are restoring some marginal debug-ability in v3, so maybe the answer is to jump on board with that as soon as it's good to go.
