### ISSUE TITLE
Tried to register two views with the same name BVLinearGradient

### ISSUE THREAD

**Issue by duckmyanmar** [alexZajac/react-native-skeleton-content-nonexpo#7]
![Screen Shot 2563-02-27 at 16 06 14](https://user-images.githubusercontent.com/61539357/75428641-1700cf80-597b-11ea-9d3d-3f705ddc3ea5.png)

I can install library is success but i can't use library help me please.

**Comment by armilano** [comment]
Can anyone solved it?

**Comment by duckmyanmar** [comment]
I have resolved the problem, because the versions library are not equal.
![Screen Shot 2563-02-27 at 17 20 22](https://user-images.githubusercontent.com/61539357/75435411-8e3b6100-5985-11ea-9b9b-c71c80486103.png)
Fix by update version
![Screen Shot 2563-02-27 at 17 24 01](https://user-images.githubusercontent.com/61539357/75435662-f427e880-5985-11ea-99bc-e93f9d778530.png)

**Comment by alexZajac** [comment]
Hey! 
This should be fixed with version 1.0.5, I have update `react-native-linear-gradient!`

**Comment by duckmyanmar** [comment]
thanks bro.

ในวันที่ พ. 4 มี.ค. 2020 เวลา 04:57 Alexandre Zajac <
notifications@github.com> เขียนว่า:
