### ISSUE TITLE
Can this support nested layouts?

### ISSUE THREAD

**Issue by hsuehic** [alexZajac/react-native-skeleton-content-nonexpo#9]
Cool work. I appreciate the component a lot. It would much better if this can support nested layout.

**Comment by hsuehic** [comment]
Item seemed that the children properties do not work as expected.

https://snack.expo.io/@hsuehic/skeleton

**Comment by alexZajac** [comment]
Hey @hsuehic! I have fixed this behavior in the latest release. Please test it and keep me updated, closing it for now.
